spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:36906/demo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
